// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsywqvffYGj_2siKTSxE61fUna9IKup20',
    appId: '1:882299507532:web:e7597cee736407a18df5e9',
    messagingSenderId: '882299507532',
    projectId: 'bookswap-j-001',
    authDomain: 'bookswap-j-001.firebaseapp.com',
    storageBucket: 'bookswap-j-001.firebasestorage.app',
    measurementId: 'G-TJGF7DMFRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoNiMB7Fn9DQFDJGylW4gD49IEC6WNs2w',
    appId: '1:882299507532:android:1dcc82498babf4d08df5e9',
    messagingSenderId: '882299507532',
    projectId: 'bookswap-j-001',
    storageBucket: 'bookswap-j-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2C4u0495n65poI98o9cNuzrLdlvp9xk',
    appId: '1:882299507532:ios:c409d74d4909f8438df5e9',
    messagingSenderId: '882299507532',
    projectId: 'bookswap-j-001',
    storageBucket: 'bookswap-j-001.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2C4u0495n65poI98o9cNuzrLdlvp9xk',
    appId: '1:882299507532:ios:c409d74d4909f8438df5e9',
    messagingSenderId: '882299507532',
    projectId: 'bookswap-j-001',
    storageBucket: 'bookswap-j-001.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsywqvffYGj_2siKTSxE61fUna9IKup20',
    appId: '1:882299507532:web:badf403d81ad512d8df5e9',
    messagingSenderId: '882299507532',
    projectId: 'bookswap-j-001',
    authDomain: 'bookswap-j-001.firebaseapp.com',
    storageBucket: 'bookswap-j-001.firebasestorage.app',
    measurementId: 'G-RX5P8QLVH6',
  );

}